name: routine
description: An app with habit tracker, task management, mood tracker, and many more features for Android, Web, and Windows.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_fonts: ^6.2.1
  dynamic_color: ^1.7.0
  flutter_screenutil: ^5.9.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  animations: ^2.0.11
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1

flutter_app_name:
  name: "Routine"

flutter_native_splash:
  color: "#F9F9F7"
  image: assets/images/icon.png
  color_dark: "#202020"
  android: true
  ios: false
  android_12:
    image: assets/images/icon.png
    icon_background_color: "#F9F9F7"
    icon_background_color_dark: "#202020"

flutter_launcher_icons:
  ios: false
  android: true
  image_path: "assets/images/icon.png"
  adaptive_icon_foreground: "assets/images/icon.png"
  remove_alpha_ios: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/icon.png
