name: Enforce Merge from Dev

on:
  pull_request:
    branches:
      - main

jobs:
  enforce-merge:
    runs-on: ubuntu-latest
    steps:
    - name: Check base branch
      if: github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref != 'dev'
      run: |
        echo "Pull requests to main can only come from dev"
        exit 1
